# src/main/resources/db.properties

db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/corporate_asset_management_db?useSSL=false&serverTimezone=UTC
db.username=root
db.password=root